version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        BACKEND_ADDRESS: ${BACKEND_ADDRESS}
    container_name: iis-frontend
    restart: "always"
    ports:
      - "3000:80" # Frontend exposed on localhost:3000
    depends_on:
      - api
    networks:
      - app-network
    

  api:
    build:
      context: ./Backend
      dockerfile: ./IISBackend.API/Dockerfile
    container_name: iis-backend-api
    restart: "always"
    ports:
      - "8003:8080"
      - "5000:5000"
    depends_on:
      - db
    environment:
      DefaultAdminPassword: ${ADMIN_PASSWORD}
      DevelopmentBucket__Enabled: ${DEVELOPMENT_BUCKET_ENABLED}
      DevelopmentBucket__Address: ${DEVELOPMENT_BUCKET_ADDRESS}
      FrontendAddress: ${FRONTEND_ADDRESS}
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ConnectionStrings__DefaultConnection: Server=db;Port=3306;Database=db;Uid=${MYSQL_USER};Pwd=${MYSQL_PASSWORD}
    volumes:
      - iis-backend-volume:/app/MockBucket
    networks:
      - app-network


  db:
    image: "mysql"
    restart: "always"
    container_name: iis-backend-dev-db
    volumes:
      - iis-backend-volume:/var/opt/mssql
    ports:
    - "1433:3306"
    environment:
      MYSQL_PORT: 3306
      MYSQL_DATABASE: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network


volumes:
  iis-backend-volume:


networks:
  app-network: