version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: IISBackend.API/Dockerfile
    container_name: iis-backend-api
    restart: "always"
    ports:
      - "127.0.0.1:8001:8080"
      - "127.0.0.1:5001:5000"
    depends_on:
      - db
    environment:
      DefaultAdminPassword: ${ADMIN_PASSWORD}
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ConnectionStrings__DefaultConnection: Server=db;Port=3306;Database=db;Uid=${MYSQL_USER};Pwd=${MYSQL_PASSWORD}
    volumes:
      - iis-backend-volume:/app/MockBucket


  db:
    image: "mysql"
    restart: "always"
    container_name: iis-backend-dev-db
    volumes:
      - iis-backend-volume:/var/opt/mssql
    ports:
    - "127.0.0.1:1433:3306"
    environment:
      MYSQL_PORT: 3306
      MYSQL_DATABASE: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}


volumes:
  iis-backend-volume: